### ISSUE TITLE
Seeing some crashes after updating to 0.1.14

### ISSUE THREAD

**Issue by nachodeh** [NiclasDev63/tiptap-extension-global-drag-handle#26]
```
SyntaxError: 'li, p:not(:first-child), pre, blockquote, h1, h2, h3, h4, h5, h6, ' is not a valid selector.
  at matches([native code])
  at find([native code])
  at <object>.props.handleDOMEvents.mousemove(./node_modules/tiptap-extension-global-drag-handle/dist/index.js:181:1)
  at f(./node_modules/prosemirror-view/dist/index.js:3083:1)
  at EditorView.someProp(./node_modules/prosemirror-view/dist/index.js:5490:1)
  at runCustomHandler(./node_modules/prosemirror-view/dist/index.js:3081:1)
  at view.input.eventHandlers[type](./node_modules/prosemirror-view/dist/index.js:3077:1)
  at sentryWrapped(./node_modules/@sentry/browser/build/npm/esm/helpers.js:96:1)
```

Reverting to v0.1.13 solves the problem

**Comment by NiclasDev63** [comment]
Just pushed commit yesterday, which should fix this issue. Try updating to .15

**Comment by nachodeh** [comment]
@NiclasDev63 still seeing the issue on 0.1.15

**Comment by NiclasDev63** [comment]
Can you share your code to reproduce the bug

**Comment by nachodeh** [comment]
Hey @NiclasDev63, this is my TipTap setup with the Drag Handle.

```
const editor = useEditor({
        extensions: [
            StarterKit,
            Link.extend({ inclusive: false }).configure({
                openOnClick: false,
                linkOnPaste: true,
            }),
            CustomKeymap,
            GlobalDragHandle,
            AutoJoiner,
            TaskList,
            TaskItem.configure({
                nested: true,
                HTMLAttributes: {
                    class: "task-item",
                },
            }),
            Markdown.configure({
                html: true,
                tightLists: true,
                bulletListMarker: "-",
                linkify: true,
            }),
        ],
        content: initialContent,
        onUpdate: ({ editor }) => {
            debouncedSaveNotesToDb(editor.getHTML(), saveEditorContent)
        },
        immediatelyRender: false,
    })
```

This is the issue as reported by Sentry, and I haven't seen it again since updating to **v0.1.13**
```
SyntaxError: Failed to execute 'matches' on 'Element': 'li, p:not(:first-child), pre, blockquote, h1, h2, h3, h4, h5, h6, ' is not a valid selector.
  at find(./node_modules/tiptap-extension-global-drag-handle/dist/index.js:27:1)
  at Array.find(<anonymous>)
  at nodeDOMAtCoords(./node_modules/tiptap-extension-global-drag-handle/dist/index.js:26:1)
  at <object>.props.handleDOMEvents.mousemove(./node_modules/tiptap-extension-global-drag-handle/dist/index.js:181:1)
  at f(./node_modules/prosemirror-view/dist/index.js:3083:1)
  at EditorView.someProp(./node_modules/prosemirror-view/dist/index.js:5490:1)
  at runCustomHandler(./node_modules/prosemirror-view/dist/index.js:3081:1)
  at view.input.eventHandlers[type](./node_modules/prosemirror-view/dist/index.js:3077:1)
  at sentryWrapped(./node_modules/@sentry/browser/build/npm/esm/helpers.js:96:1)
```

Let me know if you need any more details

**Comment by NiclasDev63** [comment]
That's strange, because I can't reproduce the error at the moment. I'll get back to it in the next few days and try to fix it.

**Comment by ShadiBlitz** [comment]
@nachodeh Which bundler do you have? Also please try to re-install your packages.

@NiclasDev63 The error is caused by an invalid CSS selector syntax in the matches function. There’s a trailing comma in the selector `li, p:not(:first-child), pre, blockquote, h1, h2, h3, h4, h5, h6, `, most likely caused by the join function.

In addition, this commit https://github.com/NiclasDev63/tiptap-extension-global-drag-handle/commit/40ef85d2345e27496f2acf5baf7855344c345b21 was probably unnecessary since the customNodes list is always initialized with default value of `[]`.

The issue here is that Array.join is being applied to the selector array, but `options.customNodes?.map` returns an array. This results in an extra comma if `customNodes` is undefined or empty, or it creates invalid syntax if not handled properly.

You can try to fix this by ensuring that `customNodes` is flattened into the selector array and excluding any undefined or empty entries. 

```typescript
function nodeDOMAtCoords(options: GlobalDragHandleOptions, coords: { x: number; y: number }) {
  const customNodeSelectors = options.customNodes?.map((node) => `[data-type=${node}]`);
  const selectors = [
    'li',
    'p:not(:first-child)',
    'pre',
    'blockquote',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    ...customNodeSelectors,
  ].join(', ');

  return document
    .elementsFromPoint(coords.x, coords.y)
    .find(
      (elem: Element) =>
        elem.parentElement?.matches?.('.ProseMirror') || elem.matches(selectors),
    );
}

```

**Comment by NiclasDev63** [comment]
We can replace
> ```ts
> options.customNodes?.map((node) => `[data-type=${node}]`) || [];
> ```
with the following 
```ts 
options.customNodes.map((node) => `[data-type=${node}]`)
```
since "customNodes" is never undefined and thus the selectors array would be.

```ts 
const selectors = [
    'li',
    'p:not(:first-child)',
    'pre',
    'blockquote',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    ...options.customNodes.map((node) => `[data-type=${node}]`),
  ].join(', ');
```
I think this should do the trick.
